

# 애플리케이션 이름 (Spring Boot에서 컨텍스트 이름으로 사용)
spring:
  application:
    name: apps3
  # 멀티파트 업로드 설정 (파일 업로드 관련)
  servlet:
    multipart:
      enabled: true
      # location: "c:\\upload"  # 임시 업로드 작업 디렉터리
      location: "/home/ec2-user/upload" 
      max-file-size: 10MB       # 단일 파일 최대 크기
      max-request-size: 30MB    # 전체 요청 최대 크기

  # Spring Cloud AWS 설정 (자동 구성 활성화)
  cloud:
    aws:
      # S3 클라이언트가 사용할 기본 리전(지역)
      region:
        static: ap-northeast-2
      # IAM 사용자 자격 증명(액세스 키와 비밀 키) 설정
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID} # 로컬 시스템에 설정된  환경변수 값으로 가져와서 입력
        secret-key: ${AWS_SECRET_ACCESS_KEY}

      # S3 작업 대상 버킷 이름
      s3:
        bucket: kth-s3-web-bucket # S3 버킷 이름을 입력 (예: kth-s3-web-bucket)
      # 스택 관련 자동 설정 비활성화
      stack:
        auto: false  # CloudFormation 스택 자동 구성을 비활성화하여 불필요한 리소스 생성을 방지

# 웹 서버 포트
server:
  port: 8080

# 사용자 정의 업로드 경로
com:
  example:
    upload:
      # path: "c:\\upload" # 로컬 테스트용 경로
      path: "/home/ec2-user/upload" #  서버 EC2에 있는 "~/upload"폴더 지정 





